Total Closer Bookings: <?php echo e($data['Total Closer Bookings']['total']); ?> (incl.
<img src="https://trademarkfactory.imgix.net/img/booking-calendar-adwords-14-7.png"/>=<?php echo e($data['Total Closer Bookings']['ga']); ?> [<?php echo e(($data['Total Closer Bookings']['total']?round(100*$data['Total Closer Bookings']['ga']/$data['Total Closer Bookings']['total'],2).'%':'N/A')); ?>]
<img src="https://trademarkfactory.imgix.net/img/booking-calendar-fb-14-7.png"/>=<?php echo e($data['Total Closer Bookings']['fb']); ?> [<?php echo e(($data['Total Closer Bookings']['total']?round(100*$data['Total Closer Bookings']['fb']/$data['Total Closer Bookings']['total'],2).'%':'N/A')); ?>]
<img src="https://trademarkfactory.imgix.net/img/booking-calendar-youtube-14-7.png"/>=<?php echo e($data['Total Closer Bookings']['yt']); ?> [<?php echo e(($data['Total Closer Bookings']['total']?round(100*$data['Total Closer Bookings']['yt']/$data['Total Closer Bookings']['total'],2).'%':'N/A')); ?>])<br/>
<?php $__currentLoopData = $data; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$details_data): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
    <?php if($loop->index): ?>
        &mdash;<?php echo e($key); ?>: <?php echo e($details_data['total']); ?> [<?php echo e(($data['Total Closer Bookings']['total']?round(100*$details_data['total']/$data['Total Closer Bookings']['total'],2).'%':'N/A')); ?>] (incl.
        <img src="https://trademarkfactory.imgix.net/img/booking-calendar-adwords-14-7.png"/>=<?php echo e($details_data['ga']); ?> [<?php echo e(($data['Total Closer Bookings']['ga']?round(100*$details_data['ga']/$data['Total Closer Bookings']['ga'],2).'%':'N/A')); ?>]
        <img src="https://trademarkfactory.imgix.net/img/booking-calendar-fb-14-7.png"/>=<?php echo e($details_data['fb']); ?> [<?php echo e(($data['Total Closer Bookings']['fb']?round(100*$details_data['fb']/$data['Total Closer Bookings']['fb'],2).'%':'N/A')); ?>]
        <img src="https://trademarkfactory.imgix.net/img/booking-calendar-youtube-14-7.png"/>=<?php echo e($details_data['yt']); ?> [<?php echo e(($data['Total Closer Bookings']['yt']?round(100*$details_data['yt']/$data['Total Closer Bookings']['yt'],2).'%':'N/A')); ?>])
        <?php if(!$loop->last): ?><br/><?php endif; ?>
    <?php endif; ?>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php /**PATH /var/www/html/in.trademarkfactory.com/resources/views/post-boom-bookings-calendar/stat/closerbookings.blade.php ENDPATH**/ ?>